server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthenticationDB
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  exchange:
    direct: "exchange-direct-auth"
    fanout: "exchange-fanout-auth"
    topic : "exchange-topic-auth"
  key:
    register: "key-auth"
  queue:
    register: "queue-auth-create-user"