server:
  port: 9091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EcCustomerDB
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
rabbitmq:
  exchange:
    direct: "exchange-direct-auth"
    fanout: "exchange-fanout-auth"
    topic : "exchange-topic-auth"
  key:
    register: "key-auth"
  queue:
    register: "queue-auth-create-customer"
jwt:
  secret: "Od%43wuj5#]Q3`Ugq_|d2~uaiKPuK2M9$y2FAQv&U5*H@wL4`BKK[>@VX-#u"